apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volmeName: "efs-static-pv"
  resources:
    requests:
      storage: 5Gi