apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
    demo: stateful-set
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None #Stateful set - headless service, so no cluster ip
  selector:
    app: nginx 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
      demo: stateful-set # has to match .spec.template.metadata.labels
  serviceName: "nginx-headless"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx
        demo: stateful-set # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
# Instead of creating pvc resource, you can directly provide in stateful set
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi